PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

CONSTRUCT {
  ?property
    rdf:type owl:DatatypeProperty ;
    rdfs:domain ?domain ;
    rdfs:subPropertyOf ?superproperty
} WHERE {
  ?property rdf:type owl:DatatypeProperty
  OPTIONAL {
    ?property rdfs:domain ?domain
  }
  OPTIONAL {
    ?property rdfs:subPropertyOf ?superproperty
  }
}
