PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

CONSTRUCT {
  ?property
    rdf:type owl:ObjectProperty ;
    rdfs:domain ?domain ;
    rdfs:range ?range ;
    rdfs:subPropertyOf ?superproperty ;
    owl:inverseOf ?inverseproperty
} WHERE {
  ?property rdf:type owl:ObjectProperty
  OPTIONAL {
    ?property rdfs:domain ?domain
  }
  OPTIONAL {
    ?property rdfs:range ?range
  }
  OPTIONAL {
    ?property rdfs:subPropertyOf ?superproperty
  }
  OPTIONAL {
    ?property owl:inverseOf ?inverseproperty
  }
}
