FROM mcr.microsoft.com/devcontainers/java

RUN sudo apt update
RUN sudo apt -y install software-properties-common

RUN sudo apt-add-repository ppa:swi-prolog/stable
RUN sudo apt update
RUN sudo apt -y install swi-prolog
